### ISSUE TITLE
Clients may request professional, paid support for Zinc Products or Services

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/zinc.coop#30]
Feature: Clients may request professional, paid support for Zinc Products or Services

  In order to get help integrating or customizing a Zinc product 
  As a Client
  I want to be able to schedule a paid support session from the website

## Notes

While we have a larger project for [allowing people to use `Support` to schedule meetings](https://github.com/orgs/zinc-collective/projects/20), I would prefer we didn't wait on this in order to get an MVP version of this out the door.

### Incremental Steps 

This is a rough sketch of the trajectory I would take on this> Feel free to pull these into their own issues or start with a pull request.

- [ ] Create a `help-and-support` landing page with a contact form (see the `/contact-us` page) that tells a visitor to fill out the form to request professional support and includes the [rate we picked for Convene and the rationality](https://github.com/zinc-collective/convene#help-and-support).
- [ ] Migrate content from `/contributing` to the `/help-and-support` page
- [ ] Add calendar events for my 10AM Sunday "Office Hours" on Twitch
- [ ] Embed the paid support scheduler (either by setting one up in Calendly _or_ waiting for Support's Scheduling feature to support paid calendar events)
